config/routes.rb
Rails.application.routes.draw do
  root 'products#index'

  devise_for :admins, controllers: {
  	sessions:      'admins/sessions',
  	passwords:     'admins/passwords',
  	registrations: 'admins/registrations'
  }
  devise_for :users, controllers: {
  	sessions:      'users/sessions',
  	passwords:     'users/passwords',
  	registrations: 'users/registrations'
  }

  get "admins/top"
  get 'products/search' => "products#search", as: "search"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

resources :users, only: [:show, :index, :edit]
resources :purchase_histories
resources :admins
resources :admins_users
resources :admins_products, only: [ :new, :create, :edit, :update, :destroy]
post 'admins_product/:id' => 'admins_products#show'
resources :carts, only: [:show]
resources :products

post '/add_content' => 'carts#add_content'
post '/update_content' => 'carts#update_content'
delete '/delete_content' => 'carts#delete_content'

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
	belongs_to :label
	has_many :products, inverse_of: :artist
	accepts_nested_attributes_for :products, reject_if: :all_blank, allow_destroy: true

	enum genre_name:{JーPOP: 0,洋楽: 1,KーPOP: 2}
end

app/models/cart.rb
class Cart < ApplicationRecord

	has_many :cart_contents, dependent: :destroy
	belongs_to :user

end

app/models/cart_content.rb
class CartContent < ApplicationRecord

	belongs_to :product
	belongs_to :cart

end

app/models/disc.rb
class Disc < ApplicationRecord
	belongs_to :product
	has_many :songs, inverse_of: :disc
	accepts_nested_attributes_for :songs, reject_if: :all_blank, allow_destroy: true

end

app/models/label.rb
class Label < ApplicationRecord
	has_many :artists, inverse_of: :label
	accepts_nested_attributes_for :artists, reject_if: :all_blank, allow_destroy: true

	enum label_name:{ユニバーサルミュージック: 0,ワーナーミュージックジャパン: 1,ソニーミュージックレーベルズ: 2,アニプレックス: 3, ポニーキャニオン: 4}

end

app/models/product.rb
class Product < ApplicationRecord
	# 下記２行cocoon記述
	has_many :discs, inverse_of: :product
	accepts_nested_attributes_for :discs, reject_if: :all_blank, allow_destroy: true

	has_many :jackets
	has_many :purchase_contents
  

	has_many :cart_contents, dependent: :destroy
	has_many :discs, dependent: :destroy
	has_many :jackets, dependent: :destroy
	has_many :purchase_histroys
	belongs_to :artist

	attachment :jacket_image_id

	enum type_name:{シングル: 0,アルバム: 1}
end

app/models/purchase_content.rb
class PurchaseContent < ApplicationRecord
	belongs_to :product
	belongs_to :purchase_history
end

app/models/purchase_history.rb
class PurchaseHistory < ApplicationRecord
	has_many :purchase_contents, dependent: :destroy
	belongs_to :user

	enum delivery_status:{受付: 0,商品準備中: 1,出荷済: 2,キャンセル: 3}
end

app/models/song.rb
class Song < ApplicationRecord

	belongs_to :disc

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :purchase_histories, dependent: :destroy
  has_one :cart

  validates :name, presence: true, length: { minimum: 2, maximum: 30 }
  validates :name_kana, presence: true, format: {with: /\A([ァ-ン]|ー)+\z/, :message =>'はカタカナで入力して下さい。'}
  validates :postal_code, presence: true, format: {with: /\A\d{3}[-]\d{4}$|^\d{3}[-]\d{2}$|^\d{3}\z/, :message =>'は有効でありません。'}
  validates :address, presence: true
  validates :tel, presence: true, format: {with: /\A[0-9]{3}-[0-9]{4}-[0-9]{4}\z/, :message =>'は有効でありません。'}

# soft_deletable

#   # Deviseを使うと、問答無用でemailがユニーク扱いになる。
#   # それだと論理削除した際に再登録できないので、一旦emailに関する検証を削除する
#   # https://gist.github.com/brenes/4503386
#   _validators.delete(:email)
#   _validate_callbacks.each do |callback|
#     if callback.raw_filter.respond_to? :attributes
#       callback.raw_filter.attributes.delete :email
#     end
#   end

#   # emailのバリデーションを定義し直す
#   validates :email, presence: true
#   validates_format_of :email, with: Devise.email_regexp, if: :email_changed?
#   validates_uniqueness_of :email, scope: :deleted_at, if: :email_changed?

#   def self.find_for_authentication(warden_conditions)
#     without_soft_destroyed.where(email: warden_conditions[:email]).first
#   end

end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController

def top
	
end

end

app/controllers/admins_users_controller.rb
class AdminsUsersController < ApplicationController
  def index
  	@users = User.all
  end

  def show
  	@user = User.find(params[:id])
  end

  def edit
  	@user = User.find(params[:id])
  end

  def update
  	@user = User.find(params[:id])
  	@user.update(user_params)
  	redirect_to admins_uesrs_path
  end

  def destroy
  	@user = User.find(params[:id])
  	@user.destroy
  	redirect_to admins_users_path
end

private
    def user_params
        params.require(:user).permit(:email, :tel, :postal_code, :address, :name_kana, :name)
    end

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  # before_action :setup_cart_content!, only: [:add_content, :update_content, :delete_content]

  def show
    if session[:user_id].nil?
    @cart = Cart.find_by(params[:id])
    @cart_contents = @cart.cart_contents
  else
    session[:user_id] = params[:user_id]
  end
end

  # 商品一覧画面から、「商品購入」を押した時のアクション
  def add_content
    if @cart_content.blank?
      @cart_content = current_cart.cart_contents.build(product_id: params[:product_id])
    end

    @cart_content.quantity += params[:item_quantity].to_i
    @cart_content.save
    redirect_to current_cart
  end

  # カート詳細画面から、「更新」を押した時のアクション
  def update_content
    @cart_content.update(item_quantity: params[:item_quantity].to_i)
    redirect_to current_cart
  end

# カート詳細画面から、「削除」を押した時のアクション
  def delete_content
    @cart_content.destroy
    redirect_to current_cart
  end

  private

  # def setup_cart_content!
  #   @cart_content = current_cart.cart_contents.find_by(product_id: params[:product_id])
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :correct_user, only: [:edit, :update ,:show]

  def cansel
  end

  def create
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to roots
  end

  def edit
    @user = User.find(params[:id])
  end

  def new
  end

  def show
    @user = User.find(params[:id])
    @q = Product.ransack(params[:q])
    @products = @q.result(distinct: true)
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to root_path
  end

  private
  def correct_user
    user = User.find(params[:id])
    if current_user != user
      redirect_to root_path
    end
  end

end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/admins_users_helper.rb
module AdminsUsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admins_users/edit.html.erb
<h2 class="text-center mx-auto pt-5 pb-3">会員情報編集</h2>

<hr>

<div class="container px-5">
<%= form_for(@user) do |f| %>

<!-- 会員登録から引用↓ -->
                      <% if @user.errors.any? %>
                        <div id="error_explanation">
                          <h2><%= @user.errors.count %>件のエラーが発生しました。</h2>
                          <ul>
                          <% @user.errors.full_messages.each do |message| %>
                            <li><%= message %></li>
                          <% end %>
                          </ul>
                        </div>
                      <% end %>

  <div class="field mt-3">
    <label for="name">名前</label><br />
    <%= f.text_field :name, autofocus: true, autocomplete: "name", placeholder: "名前(姓名)", class: "pl-2", id: "name" %>
  </div>

  <div class="field mt-1">
    <%= f.text_field :name_kana, autocomplete: "name_kana", placeholder: "名前(セイメイ)", class: "pl-2", id: "name_kana" %>
  </div>

  <div class="field mt-4">
    <label for="postal_code">郵便番号</label><br />
    <%= f.text_field :postal_code, placeholder: "（例）000-0000", class: "pl-2", id: "postal_code" %>
  </div>

  <div class="field mt-4">
    <label for="address">住所</label><br />
    <%= f.text_field :address, placeholder: "住所", class: "pl-2", id: "address" %>
  </div>

  <div class="field mt-4">
    <label for="tel">電話番号</label><br />
    <%= f.telephone_field :tel, placeholder: "（例）000-0000-0000", class: "pl-2", id: "tel" %>
  </div>

  <div class="field mt-4">
    <label for="email">メールアドレス</label><br />
    <%= f.email_field :email, placeholder: "（例）XXX@XXX.com", class: "pl-2", id: "email" %>
  </div>

  <div class="field mt-4">
    <label for="password">パスワード</label>
    <% if @minimum_password_length %>
    <em>(<%= @minimum_password_length %> characters minimum)</em>
    <% end %><br />
    <%= f.password_field :password, autocomplete: "new-password", placeholder: "パスワード", class: "pl-2", id: "password" %>
  </div>

  <div class="actions">
    <div class="mx-auto text-center">
      <%= f.submit "編集", class: "btn btn-primary col-6 my-4 py-3" %>
    </div>
  </div>


<% end %>

<%= link_to "Back", :back %>

</div>

app/views/admins_users/index.html.erb
<head>
	<meta charset="utf-8">
	<title></title>
<!-- 	<link href="css/bootstrap.css" rel="stylesheet"> -->
</head>

<header id="header">
	<%= link_to root_path do %>
		<button type="button" style="padding: 15px" class="btn page-link text-dark d-inline-block btn-lg btn-block">
			<font size="7">カラオケばっちこい！</font>
		</button>
	<% end %>
	<div class="link_top">
		<%= link_to admins_top_path do %>
			<button type="button" style="padding: 20px 100px; margin-bottom: 40px; " class="btn page-link text-dark d-inline-block btn-lg center-block"><p style="margin: 0;"class="text-primary">管理者トップページへ</p>
			</button>
		<% end %>
	</div>
</header><!-- /header -->
<body>
	<div class="container">
		<div class="row">
			<div class="col-md-10 offset-md-1">
				<h1>ユーザー一覧</h1>
				<% @users.each do |user| %>
				<div class="admin-users-index-box clearfix">
					<div class="admin-users-info-box">
						<div class="boxboxbox clearfix">
							<div class="name-box">名前</div>
							<div class="name-text-boxbox clearfix">
								<div class="name-text-box"><%= user.name %></div>
								<div class="name-text-box"><%= user.name_kana %></div>
							</div>
							<div class="postal_code-box">〒<%= user.postal_code %></div>
						</div>
						<div class="E-T-P-boxbox">
							<div class="E-T-P-box">Email</div>
							<div class="E-T-P-box">TEL</div>
						</div>
						<div class="E-T-P-text-boxbox">
							<div class="E-T-P-text-box"><%= user.email%></div>
							<div class="E-T-P-text-box"><%= user.tel%></div>
						</div>
						<div class="addresses-box"><%= user.address %></div>
					</div>
					<div class="btn-group-vertical" style="margin: -160px 11px 60px 502px;" role="group">
					<%=  link_to admins_user_path(user.id) do %><button type="button" style="padding: 6px 20px; background-color: red;
					margin-bottom: 10px;" class="btn page-link text-dark d-inline-block">購入履歴</button> <% end %>
					<%= link_to edit_admins_user_path(user.id) do %><button type="button" style="padding: 6px 36px; background-color: green;
					margin-bottom: 10px;" class="btn page-link text-dark d-inline-block">編集</button> <% end %>
					<%=  link_to admins_user_path(user.id), method: :delete do %><button type="button" style="padding: 6px 36px; background-color: blue;
					margin-bottom: 10px;" class="btn page-link text-dark d-inline-block">削除</button> <% end %>
					</div>
				</div>
				<% end %>
			</div>
		</div>
	</div>
</body>

app/views/admins_users/show.html.erb
<header id="header">
	<%= link_to root_path do %>
		<button type="button" style="padding: 15px" class="btn page-link text-dark d-inline-block btn-lg btn-block">
			<font size="7">カラオケばっちこい！</font>
		</button>
	<% end %>
	<div class="link_top">
		<%= link_to admins_top_path do %>
			<button type="button" style="padding: 20px 100px; margin-bottom: 40px; " class="btn page-link text-dark d-inline-block btn-lg center-block"><p style="margin: 0;"class="text-primary">管理者トップページへ</p>
			</button>
		<% end %>
	</div>
</header><!-- /header -->
<% @user.purchase_histories.each do |history| %>
<% sum_price = 0 %>
<table class="table table-bordered my-3"">
		<tr>
		<th>購入者</th>
		<td><%= @user.name %></td>
		</tr>
		<tr>
		<th>購入日</th>
		<td><%= history.created_at %></td>
		</tr>
	<tr>
		<th>購入内容</th>
		<td>
		<ul>
			<% history.purchase_contents.each do |content| %>

				<li><%= content.product.product_name %></li>
					<li>購入枚数 <%= content.item_quantity %>枚</li>
					<li class="text-right">小計 <%= content.purchase_unit_price * content.item_quantity %></li>
				<% sum_price += content.purchase_unit_price * content.item_quantity %>
				<div class="hr my-3"><hr></div>
			<% end %>
		</ul>
	</tr>
		<tr>
		<th>送付先</th>
		<td><%= history.destination_address %></td>
		</tr>
		<tr>
		<th>ステータス</th>
		<td><%= history.delivery_status %></td>
		</tr>
	</table>

	<li class="text-right">合計金額<%= sum_price %></li>
	<% end %>