config/routes.rb
Rails.application.routes.draw do
  root 'products#index'

  devise_for :admins, controllers: {
  	sessions:      'admins/sessions',
  	passwords:     'admins/passwords',
  	registrations: 'admins/registrations'
  }
  devise_for :users, controllers: {
  	sessions:      'users/sessions',
  	passwords:     'users/passwords',
  	registrations: 'users/registrations'
  }

  get "admins/top"
  get 'products/search' => "products#search", as: "search"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

resources :users, only: [:show, :index, :edit]
resources :purchase_histories
resources :admins
resources :admins_users
resources :admins_products, only: [ :new, :create, :edit, :update, :destroy]
post 'admins_product/:id' => 'admins_products#show'
resources :carts, only: [:show]
resources :products

post '/add_content' => 'carts#add_content'
post '/update_content' => 'carts#update_content'
delete '/delete_content' => 'carts#delete_content'

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
	belongs_to :label
	has_many :products, inverse_of: :artist
	accepts_nested_attributes_for :products, reject_if: :all_blank, allow_destroy: true

	enum genre_name:{JーPOP: 0,洋楽: 1,KーPOP: 2}
end

app/models/cart.rb
class Cart < ApplicationRecord

	has_many :cart_contents, dependent: :destroy
	belongs_to :user

end

app/models/cart_content.rb
class CartContent < ApplicationRecord

	belongs_to :product
	belongs_to :cart

end

app/models/disc.rb
class Disc < ApplicationRecord
	belongs_to :product
	has_many :songs, inverse_of: :disc
	accepts_nested_attributes_for :songs, reject_if: :all_blank, allow_destroy: true

end

app/models/label.rb
class Label < ApplicationRecord
	has_many :artists, inverse_of: :label
	accepts_nested_attributes_for :artists, reject_if: :all_blank, allow_destroy: true

	enum label_name:{ユニバーサルミュージック: 0,ワーナーミュージックジャパン: 1,ソニーミュージックレーベルズ: 2,アニプレックス: 3, ポニーキャニオン: 4}

end

app/models/product.rb
class Product < ApplicationRecord
	# 下記２行cocoon記述
	has_many :discs, inverse_of: :product
	accepts_nested_attributes_for :discs, reject_if: :all_blank, allow_destroy: true

	has_many :jackets
	has_many :purchase_contents
  

	has_many :cart_contents, dependent: :destroy
	has_many :discs, dependent: :destroy
	has_many :jackets, dependent: :destroy
	has_many :purchase_histroys
	belongs_to :artist

	attachment :jacket_image_id

	enum type_name:{シングル: 0,アルバム: 1}
end

app/models/purchase_content.rb
class PurchaseContent < ApplicationRecord
	belongs_to :product
	belongs_to :purchase_history
end

app/models/purchase_history.rb
class PurchaseHistory < ApplicationRecord
	has_many :purchase_contents, dependent: :destroy
	belongs_to :user

	enum delivery_status:{受付: 0,商品準備中: 1,出荷済: 2,キャンセル: 3}
end

app/models/song.rb
class Song < ApplicationRecord

	belongs_to :disc

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :purchase_histories, dependent: :destroy
  has_one :cart

  validates :name, presence: true, length: { minimum: 2, maximum: 30 }
  validates :name_kana, presence: true, format: {with: /\A([ァ-ン]|ー)+\z/, :message =>'はカタカナで入力して下さい。'}
  validates :postal_code, presence: true, format: {with: /\A\d{3}[-]\d{4}$|^\d{3}[-]\d{2}$|^\d{3}\z/, :message =>'は有効でありません。'}
  validates :address, presence: true
  validates :tel, presence: true, format: {with: /\A[0-9]{3}-[0-9]{4}-[0-9]{4}\z/, :message =>'は有効でありません。'}

# soft_deletable

#   # Deviseを使うと、問答無用でemailがユニーク扱いになる。
#   # それだと論理削除した際に再登録できないので、一旦emailに関する検証を削除する
#   # https://gist.github.com/brenes/4503386
#   _validators.delete(:email)
#   _validate_callbacks.each do |callback|
#     if callback.raw_filter.respond_to? :attributes
#       callback.raw_filter.attributes.delete :email
#     end
#   end

#   # emailのバリデーションを定義し直す
#   validates :email, presence: true
#   validates_format_of :email, with: Devise.email_regexp, if: :email_changed?
#   validates_uniqueness_of :email, scope: :deleted_at, if: :email_changed?

#   def self.find_for_authentication(warden_conditions)
#     without_soft_destroyed.where(email: warden_conditions[:email]).first
#   end

end

app/controllers/admins_products_controller.rb
class AdminsProductsController < ApplicationController

  def new
  	@product = Product.new
    @disc = @product.discs.build
    @song = @disc.songs.build
  end

  def create
  	product = Product.new(product_params)
  	label.save
  	render :show
  end


  def show
  	@product = Product.find(params[:id])
  end

  def edit
  end

  private
  def product_params
  # params.require(:モデル名).permit(:カラム名1, :カラム名2, ...)
  	params.require(:product).permit(:product_name, :type_name, :price, :number_of_stock, :artist_id, :jacket_image_id, :product_introduction, :staff_comment, disc_attributes: [:id, :disc_order, :disc_name, :product_id, song_attributes: [:id, :song_name1, :song_name2, :song_name3, :song_name4, :song_name5, :song_name6, :song_name7, :song_name8, :song_name9, :song_name10, :song_name11, :song_name12, :song_name13, :song_name14, :song_name15, :song_name16, :song_name17, :song_name18, :song_name19, :song_name20, :disc_id]])
  end

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  # before_action :setup_cart_content!, only: [:add_content, :update_content, :delete_content]

  def show
    if session[:user_id].nil?
    @cart = Cart.find_by(params[:id])
    @cart_contents = @cart.cart_contents
  else
    session[:user_id] = params[:user_id]
  end
end

  # 商品一覧画面から、「商品購入」を押した時のアクション
  def add_content
    if @cart_content.blank?
      @cart_content = current_cart.cart_contents.build(product_id: params[:product_id])
    end

    @cart_content.quantity += params[:item_quantity].to_i
    @cart_content.save
    redirect_to current_cart
  end

  # カート詳細画面から、「更新」を押した時のアクション
  def update_content
    @cart_content.update(item_quantity: params[:item_quantity].to_i)
    redirect_to current_cart
  end

# カート詳細画面から、「削除」を押した時のアクション
  def delete_content
    @cart_content.destroy
    redirect_to current_cart
  end

  private

  # def setup_cart_content!
  #   @cart_content = current_cart.cart_contents.find_by(product_id: params[:product_id])
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :correct_user, only: [:edit, :update ,:show]

  def cansel
  end

  def create
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to roots
  end

  def edit
    @user = User.find(params[:id])
  end

  def new
  end

  def show
    @user = User.find(params[:id])
    @q = Product.ransack(params[:q])
    @products = @q.result(distinct: true)
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to root_path
  end

  private
  def correct_user
    user = User.find(params[:id])
    if current_user != user
      redirect_to root_path
    end
  end

end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/admins_products_helper.rb
module AdminsProductsHelper
end

app/helpers/admins_users_helper.rb
module AdminsUsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admins_products/edit.html.erb
<div class="container" style="width:800px;">

<div class="text-center mx-auto my-4">
 <button type="button" class="btn btn-lg btn-primary">管理者トップページへ</button>
</div>




<%=form_for @label,:url =>'product_path' do |f| %>
    <h3>商品の編集</h3>
    <div class="card p-3">
      <div class="form-group">

              <div class="form-group mt-3">
                <label for="inputsabel">レーベル名</label>
                <%= f.text_field :label_name, placeholder: "レーベル名", class: "pl-2" %>
<!--                  <input type="text" class="form-control" id="inputLabel" placeholder="レーベル名"> -->
              </div>


          <%=form_for :artists do |artist| %>
          <!-- <%#= attachment_image_tag book.user, :image, :fill, 100, 100, format: 'jpeg',fallback: "no_image.jpg", :size =>"50x50" %> -->
          <!-- <input type="file" class="form-control-file" id="File"> -->
          <div class="form-group">
            <label for="inputArtists">アーティスト名</label>
            <%= artist.text_field :artist_name, placeholder: "アーティスト名", class: "pl-2" %>
          </div>



          <%=artist.fields_for :products do |product| %>

              <div class="form-group">
                <label for="File">シングル名/アルバム名</label><br />
                <%= product.text_field :product_name %>
              </div>

              <div class="form-group">
                <label for="File">ジャケット画像</label>
                <%= product.attachment_field :jacket_image_id %>
              </div>

              <div class="form-group">
                <label for="inputPrice">価格</label>
                <div class="input-group">
                  <%= product.text_field :price, placeholder: "価格", class:"pl-2"%>
                  <div class="ml-2">円</div>
                </div>
              </div>
                <!-- <input type="text" class="form-control" id="inputDiscs" placeholder="ここにシングル/アルバム名を記入"> -->

                  <!-- <div class="form-group">
                      <%# f.fields_for :songs do |song| %>
                      <%#= f.label :アーティスト名%>
                    <%#= song.text_field :song_name %> -->
                    <!-- <input type="text" class="form-control" id="inputArtists" placeholder="ここにアーティスト名を記入"> -->
                    <!--<%# end %>
                  </div> -->


              <div class="form-group">
                <label for="exampleSelect1exampleFormControlSelect1">在庫数</label>
                <div class="input-group">
                  <select class="form-control col-1" id="exampleFormControlSelect1">
                    <option>1</option>
                    <option>2</option>
                    <option>3</option>
                    <option>4</option>
                    <option>5</option>
                  </select>
                  <div class="ml-2">個</div>
                </div>
              </div>

              <div class="form-group">
                <div>ジャンル</div>
                <div class="form-check form-check-inline">
                  <input class="form-check-input" type="radio" name="inlineRadioOptions" id="inlineRadio1" value="option1">
                  <label class="form-check-label" for="inlineRadio1">J-POP</label>
                </div>
                <div class="form-check form-check-inline">
                  <input class="form-check-input" type="radio" name="inlineRadioOptions" id="inlineRadio2" value="option2">
                  <label class="form-check-label" for="inlineRadio2">K-POP</label>
                </div>
                <div class="form-check form-check-inline">
                  <input class="form-check-input" type="radio" name="inlineRadioOptions" id="inlineRadio3" value="option3">
                  <label class="form-check-label" for="inlineRadio3">洋楽</label>
                </div>
              </div>



              <div class="form-group">
                <label for="exampleFormControlTextarea1">商品詳細</label>
                <%= product.text_area :product_introduction, placeholder: "ここに商品の詳細を記入", class: "pl-2" %>
        <!-- <textarea class="form-control" id="exampleFormControlTextarea1" rows="3" placeholder="ここに商品の詳細を記入"></textarea> -->
              </div>

              <div class="form-group">
                <label for="exampleFormControlTextarea1">スタッフコメント</label>
                <%= product.text_area :staff_coment, placeholder: "ここにスタッフコメントを記入", class: "pl-2" %>
                <!-- <textarea class="form-control" id="exampleFormControlTextarea1" rows="3" placeholder="ここにスタッフコメントを記入"></textarea> -->
              </div>

              <%= product.fields_for :discs do |disc| %>

                <%= disc.text_field :disc_name, placeholder: "ここにディスクタイトルを記入", class: "pl-2" %>

                  <p>シングル/アルバム内のコンテンツ</p>
                  <div class="card p-3 mb-3">
                      <% disc.fields_for :songs do |song| %>

                        <form class="form-inline">
                          <div class="form-group input-group mb-2">
                              <%= song.text_field :song_name, valu: "ここに曲名を追加" %>

                            <button type="submit" class="btn btn-primary col-2 ml-1">追加</button>
                            <button type="submit" class="btn btn-danger col-2 ml-1">削除</button>
                          </div>
                        </form>

                      <% end %><!-- fields_for song -->
                    <div class="text-center mx-auto my-2">
                    <button type="submit" class="btn btn-lg btn-primary">曲目を増やす</button>
                    </div>
                  </div><!-- card110line -->

                  <div class="text-center mx-auto my-3">
                    <button type="submit" class="btn btn-lg btn-primary">DISCを増やす</button>
                  </div>

                  <div class="text-center mx-auto my-3">
                    <button type="submit" class="btn btn-lg btn-primary">編集する</button>
                  </div>


              <% end %><!-- fields_for disc -->
          <% end %><!-- fields_for product -->


      </div>
    </div><!-- card 13line-->

app/views/admins_products/label_artist.html.erb
<%=form_for @label,:url =>'product_path' do |f| %>
    <h3>商品の新規追加</h3>
    <div class="card p-3">
      <div class="form-group">

              <div class="form-group mt-3">
                <label for="inputsabel">レーベル名</label>
                <%= f.text_field :label_name, placeholder: "レーベル名", class: "pl-2" %>
<!--                  <input type="text" class="form-control" id="inputLabel" placeholder="レーベル名"> -->
              </div>


          <%=f.fields_for :artists do |artist| %>
          <!-- <%#= attachment_image_tag book.user, :image, :fill, 100, 100, format: 'jpeg',fallback: "no_image.jpg", :size =>"50x50" %> -->
          <!-- <input type="file" class="form-control-file" id="File"> -->
          <div class="form-group">
            <label for="inputArtists">アーティスト名</label>
            <%= artist.text_field :artist_name, placeholder: "アーティスト名", class: "pl-2" %>
          </div>
          <% end %>
<% end %>

app/views/admins_products/new.html.erb
<div class="container" style="width:800px;">

<div class="text-center mx-auto my-4">
 <button type="button" class="btn btn-lg btn-primary">管理者トップページへ</button>
</div>








          <%=form_for @product do |f| %>

              <div class="form-group">
                <label for="File">シングル名/アルバム名</label><br />
                <%= f.text_field :product_name %>
              </div>

              <div class="form-group">
                <label for="File">ジャケット画像</label>
                <%= f.attachment_field :jacket_image_id %>
              </div>

              <div class="form-group">
                <label for="inputPrice">価格</label>
                <div class="input-group">
                  <%= f.text_field :price, placeholder: "価格", class:"pl-2"%>
                  <div class="ml-2">円</div>
                </div>
              </div>

              <div class="form-group">
                <label for="exampleSelect1exampleFormControlSelect1">在庫数</label>
                <div class="input-group">
                  <select class="form-control col-1" id="exampleFormControlSelect1">
                    <option>1</option>
                    <option>2</option>
                    <option>3</option>
                    <option>4</option>
                    <option>5</option>
                  </select>
                  <div class="ml-2">個</div>
                </div>
              </div>

              <div class="form-group">
                <div>ジャンル</div>
                <div class="form-check form-check-inline">
                  <input class="form-check-input" type="radio" name="inlineRadioOptions" id="inlineRadio1" value="option1">
                  <label class="form-check-label" for="inlineRadio1">J-POP</label>
                </div>
                <div class="form-check form-check-inline">
                  <input class="form-check-input" type="radio" name="inlineRadioOptions" id="inlineRadio2" value="option2">
                  <label class="form-check-label" for="inlineRadio2">K-POP</label>
                </div>
                <div class="form-check form-check-inline">
                  <input class="form-check-input" type="radio" name="inlineRadioOptions" id="inlineRadio3" value="option3">
                  <label class="form-check-label" for="inlineRadio3">洋楽</label>
                </div>
              </div>



              <div class="form-group">
                <label for="exampleFormControlTextarea1">商品詳細</label>
                <%= f.text_area :product_introduction, placeholder: "ここに商品の詳細を記入", class: "pl-2" %>
              </div>

              <div class="form-group">
                <label for="exampleFormControlTextarea1">スタッフコメント</label>
                <%= f.text_area :staff_comment, placeholder: "ここにスタッフコメントを記入", class: "pl-2" %>
              </div>

              <div class="form-group">
                <label for="exampleFormControlTextarea1">スタッフコメント</label>
              <%= f.fields_for :discs do |disc| %>

              <%= disc.text_field :disc_name, placeholder: "ディスクタイトル", class: "pl-2" %>
              </div>

              <div class="form-group">
                <label for="exampleFormControlTextarea1">スタッフコメント</label>
                <%= disc.fields_for :songs do |song| %>
                <%= song.text_area :song_name1, placeholder: "ソングタイトル", class: "pl-2" %>
              </div>

              <div class="form-group">
                <label for="exampleFormControlTextarea1">スタッフコメント</label>
                <%= song.text_area :song_name2, placeholder: "ソングタイトル", class: "pl-2" %>
              </div>

              <div class="form-group">
                <label for="exampleFormControlTextarea1">スタッフコメント</label>
                <%= song.text_area :song_name3, placeholder: "ソングタイトル", class: "pl-2" %>
              </div>

              <div class="form-group">
                <label for="exampleFormControlTextarea1">スタッフコメント</label>
                <%= song.text_area :song_name4, placeholder: "ソングタイトル", class: "pl-2" %>
              </div>

              <div class="form-group">
                <label for="exampleFormControlTextarea1">スタッフコメント</label>
                <%= song.text_area :song_name5, placeholder: "ソングタイトル", class: "pl-2" %>
              </div>

              <div class="form-group">
                <label for="exampleFormControlTextarea1">スタッフコメント</label>
                <%= song.text_area :song_name6, placeholder: "ソングタイトル", class: "pl-2" %>
              </div>

              <div class="form-group">
                <label for="exampleFormControlTextarea1">スタッフコメント</label>
                <%= song.text_area :song_name7, placeholder: "ソングタイトル", class: "pl-2" %>
              </div>

              <div class="form-group">
                <label for="exampleFormControlTextarea1">スタッフコメント</label>
                <%= song.text_area :song_name8, placeholder: "ソングタイトル", class: "pl-2" %>
              </div>

              <div class="form-group">
                <label for="exampleFormControlTextarea1">スタッフコメント</label>
                <%= song.text_area :song_name9, placeholder: "ソングタイトル", class: "pl-2" %>
              </div>

              <div class="form-group">
                <label for="exampleFormControlTextarea1">スタッフコメント</label>
                <%= song.text_area :song_name10, placeholder: "ソングタイトル", class: "pl-2" %>
              </div>

              <div class="form-group">
                <label for="exampleFormControlTextarea1">スタッフコメント</label>
                <%= song.text_area :song_name11, placeholder: "ソングタイトル", class: "pl-2" %>
              </div>

              <div class="form-group">
                <label for="exampleFormControlTextarea1">スタッフコメント</label>
                <%= song.text_area :song_name12, placeholder: "ソングタイトル", class: "pl-2" %>
              </div>

              <div class="form-group">
                <label for="exampleFormControlTextarea1">スタッフコメント</label>
                <%= song.text_area :song_name13, placeholder: "ソングタイトル", class: "pl-2" %>
              </div>

              <div class="form-group">
                <label for="exampleFormControlTextarea1">スタッフコメント</label>
                <%= song.text_area :song_name14, placeholder: "ソングタイトル", class: "pl-2" %>
              </div>

              <div class="form-group">
                <label for="exampleFormControlTextarea1">スタッフコメント</label>
                <%= song.text_area :song_name15, placeholder: "ソングタイトル", class: "pl-2" %>
              </div>

              <div class="form-group">
                <label for="exampleFormControlTextarea1">スタッフコメント</label>
                <%= song.text_area :song_name16, placeholder: "ソングタイトル", class: "pl-2" %>
              </div>

              <div class="form-group">
                <label for="exampleFormControlTextarea1">スタッフコメント</label>
                <%= song.text_area :song_name17, placeholder: "ソングタイトル", class: "pl-2" %>
              </div>

              <div class="form-group">
                <label for="exampleFormControlTextarea1">スタッフコメント</label>
                <%= song.text_area :song_name18, placeholder: "ソングタイトル", class: "pl-2" %>
              </div>

              <div class="form-group">
                <label for="exampleFormControlTextarea1">スタッフコメント</label>
                <%= song.text_area :song_name19, placeholder: "ソングタイトル", class: "pl-2" %>
              </div>

              <div class="form-group">
                <label for="exampleFormControlTextarea1">スタッフコメント</label>
                <%= song.text_area :song_name20, placeholder: "ソングタイトル", class: "pl-2" %>
              </div>

              <% end %><!-- song -->
          <% end %><!-- disc -->
          <%= f.submit "クリエイト" %>
          <% end %>


      </div>
    </div><!-- card 13line-->

app/views/admins_products/show.html.erb
<header id="header">
	<%= link_to root_path do %>
		<button type="button" style="padding: 15px" class="btn page-link text-dark d-inline-block btn-lg btn-block">
			<font size="7">カラオケばっちこい！</font>
		</button>
	<% end %>
	<div class="link_top">
		<%= link_to admins_top_path do %>
			<button type="button" style="padding: 20px 100px; margin-bottom: 40px; " class="btn page-link text-dark d-inline-block btn-lg center-block"><p style="margin: 0;"class="text-primary">管理者トップページへ</p>
			</button>
		<% end %>
	</div>
</header><!-- /header -->
<body>
	<div class="container">
		<div class="row">
			<div class="col-md-8 offset-md-2">
				<div class="box clearfix">
					<div class="jacket-box">
						<div class="type-name">
							[CD]<%= @product.type_name %>
						</div>
						<div class="jacket-jpg">
							<%#= attachment_image_tag, @product. :image, :fill, 100, 100, format: 'jpeg',fallback: "no_image.jpg", :size =>"50x50" %>画像
						</div>
					</div>
					<div class="product-content-box">
						<p>アルバム名<%= @product.product_name %></p>
						<p>アーティスト名
							<%= @product.artist.artist_name %></p>
						<p><%= @product.price %>価格（税込み）</p>
						<p>在庫状況<%= @product.number_of_stock %></p>
						<%= link_to edit_admins_product_path(@product.id) do %><button type="button" class="btn page-link text-dark d-inline-block btn-lg center-block">
						<p style="margin: 0;" class="text-primary">編集する</p>
						</button><% end %>
					</div>
				</div>
				<div class="box2">
					<p>ジャンル名<%= @product.artist.genre_name %></p>
					<p>レーベル<%= @product.artist.label.label_name %></p>
				</div>
				<% @product.discs.each do |disc| %>
				<div class="song-name-box">
					<table>
						<h3><%= disc.disc_name %></h3>
						<tbody>
							<% disc.songs.each do |song| %>
							<tr>
								<td><%= song.song_name %></td>
							</tr>
							<% end %>
						</tbody>
					</table>
				</div>
				<% end %>
				<div class="product-content-box2">
					<p>商品詳細</p>
    				<%= @product.product_introduction %>
				</div>
				<div class="staff-comment">
					<h5>スタッフコメント</h5>
					<%= @product.staff_comment %>
				</div>
			</div>
		</div>
	</div>
</body>