config/routes.rb
Rails.application.routes.draw do
  root 'products#index'

  devise_for :admins, controllers: {
  	sessions:      'admins/sessions',
  	passwords:     'admins/passwords',
  	registrations: 'admins/registrations'
  }
  devise_for :users, controllers: {
  	sessions:      'users/sessions',
  	passwords:     'users/passwords',
  	registrations: 'users/registrations'
  }

  get "admins/top"
  get 'products/search' => "products#search", as: "search"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

resources :users, only: [:show, :index, :edit]
resources :purchase_histories
resources :admins
resources :admins_users
resources :admins_products, only: [ :new, :create, :edit, :update, :destroy]
post 'admins_product/:id' => 'admins_products#show'
resources :carts, only: [:show]
resources :products

post '/add_content' => 'carts#add_content'
post '/update_content' => 'carts#update_content'
delete '/delete_content' => 'carts#delete_content'

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
	belongs_to :label
	has_many :products, inverse_of: :artist
	accepts_nested_attributes_for :products, reject_if: :all_blank, allow_destroy: true

	enum genre_name:{JーPOP: 0,洋楽: 1,KーPOP: 2}
end

app/models/cart.rb
class Cart < ApplicationRecord

	has_many :cart_contents, dependent: :destroy
	belongs_to :user

end

app/models/cart_content.rb
class CartContent < ApplicationRecord

	belongs_to :product
	belongs_to :cart

end

app/models/disc.rb
class Disc < ApplicationRecord
	belongs_to :product
	has_many :songs, inverse_of: :disc
	accepts_nested_attributes_for :songs, reject_if: :all_blank, allow_destroy: true

end

app/models/label.rb
class Label < ApplicationRecord
	has_many :artists, inverse_of: :label
	accepts_nested_attributes_for :artists, reject_if: :all_blank, allow_destroy: true

	enum label_name:{ユニバーサルミュージック: 0,ワーナーミュージックジャパン: 1,ソニーミュージックレーベルズ: 2,アニプレックス: 3, ポニーキャニオン: 4}

end

app/models/product.rb
class Product < ApplicationRecord
	# 下記２行cocoon記述
	has_many :discs, inverse_of: :product
	accepts_nested_attributes_for :discs, reject_if: :all_blank, allow_destroy: true

	has_many :jackets
	has_many :purchase_contents
  

	has_many :cart_contents, dependent: :destroy
	has_many :discs, dependent: :destroy
	has_many :jackets, dependent: :destroy
	has_many :purchase_histroys
	belongs_to :artist

	attachment :jacket_image_id

	enum type_name:{シングル: 0,アルバム: 1}
end

app/models/purchase_content.rb
class PurchaseContent < ApplicationRecord
	belongs_to :product
	belongs_to :purchase_history
end

app/models/purchase_history.rb
class PurchaseHistory < ApplicationRecord
	has_many :purchase_contents, dependent: :destroy
	belongs_to :user

	enum delivery_status:{受付: 0,商品準備中: 1,出荷済: 2,キャンセル: 3}
end

app/models/song.rb
class Song < ApplicationRecord

	belongs_to :disc

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :purchase_histories, dependent: :destroy
  has_one :cart

  validates :name, presence: true, length: { minimum: 2, maximum: 30 }
  validates :name_kana, presence: true, format: {with: /\A([ァ-ン]|ー)+\z/, :message =>'はカタカナで入力して下さい。'}
  validates :postal_code, presence: true, format: {with: /\A\d{3}[-]\d{4}$|^\d{3}[-]\d{2}$|^\d{3}\z/, :message =>'は有効でありません。'}
  validates :address, presence: true
  validates :tel, presence: true, format: {with: /\A[0-9]{3}-[0-9]{4}-[0-9]{4}\z/, :message =>'は有効でありません。'}

# soft_deletable

#   # Deviseを使うと、問答無用でemailがユニーク扱いになる。
#   # それだと論理削除した際に再登録できないので、一旦emailに関する検証を削除する
#   # https://gist.github.com/brenes/4503386
#   _validators.delete(:email)
#   _validate_callbacks.each do |callback|
#     if callback.raw_filter.respond_to? :attributes
#       callback.raw_filter.attributes.delete :email
#     end
#   end

#   # emailのバリデーションを定義し直す
#   validates :email, presence: true
#   validates_format_of :email, with: Devise.email_regexp, if: :email_changed?
#   validates_uniqueness_of :email, scope: :deleted_at, if: :email_changed?

#   def self.find_for_authentication(warden_conditions)
#     without_soft_destroyed.where(email: warden_conditions[:email]).first
#   end

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  # before_action :setup_cart_content!, only: [:add_content, :update_content, :delete_content]

  def show
    if session[:user_id].nil?
    @cart = Cart.find_by(params[:id])
    @cart_contents = @cart.cart_contents
  else
    session[:user_id] = params[:user_id]
  end
end

  # 商品一覧画面から、「商品購入」を押した時のアクション
  def add_content
    if @cart_content.blank?
      @cart_content = current_cart.cart_contents.build(product_id: params[:product_id])
    end

    @cart_content.quantity += params[:item_quantity].to_i
    @cart_content.save
    redirect_to current_cart
  end

  # カート詳細画面から、「更新」を押した時のアクション
  def update_content
    @cart_content.update(item_quantity: params[:item_quantity].to_i)
    redirect_to current_cart
  end

# カート詳細画面から、「削除」を押した時のアクション
  def delete_content
    @cart_content.destroy
    redirect_to current_cart
  end

  private

  # def setup_cart_content!
  #   @cart_content = current_cart.cart_contents.find_by(product_id: params[:product_id])
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :correct_user, only: [:edit, :update ,:show]

  def cansel
  end

  def create
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to roots
  end

  def edit
    @user = User.find(params[:id])
  end

  def new
  end

  def show
    @user = User.find(params[:id])
    @q = Product.ransack(params[:q])
    @products = @q.result(distinct: true)
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to root_path
  end

  private
  def correct_user
    user = User.find(params[:id])
    if current_user != user
      redirect_to root_path
    end
  end

end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/admins_users_helper.rb
module AdminsUsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admins/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>

app/views/admins/top.html.erb
<body>
	<div class="container">
		<div class="row">
			<div class="col-*-6 offset-*-3" style="margin: 70px 160px;">
				<h1 class="top-h1">管理者トップページ
				</h1>
				<%= link_to admins_users_path do %>
				<button type="button" style="padding: 20px 100px; margin-bottom: 40px; " class="btn page-link text-dark d-inline-block btn-lg center-block"><p style="margin: 0;"class="text-primary">ユーザー一覧ページへ</p>
				</button>
				<% end %>
				<%= link_to purchase_histories_path do %>
				<button type="button" style="padding: 20px 100px; margin-bottom: 40px; " class="btn page-link text-dark d-inline-block btn-lg center-block"><p style="margin: 0;"class="text-primary">ユーザーの購入履歴ページへ</p>
				</button>
				<% end %>
				<%= link_to new_admins_product_path do %>
				<button type="button" style="padding: 20px 100px; margin-bottom: 40px; " class="btn page-link text-dark d-inline-block btn-lg center-block"><p style="margin: 0;"class="text-primary">商品追加ページへ</p>
				</button>
				<% end %>
			</div>
		</div>
	</div>
</body>

app/views/layouts/_header.html.erb
<header>
  <nav class="bg-warning sticky-top p-2 text-center">
  	<%= link_to root_path do %>
  	<div class="text-light">カラオケばっちこい！</div>
  	<% end %>
  </nav>
</header>

<ul class="nav-menu clearfix">
<% if user_signed_in? %>
  <!-- ログイン時 -->
	<!-- ユーザーのカート内ページに遷移 -->
	<%= link_to cart_path(current_user.id) , class: 'nav-text' do  %>
	  <li class="nav-list">
	  <%= image_tag 'cart.png' %>
	  <br>カート
	  </li>
	<% end %>

	<%= link_to destroy_user_session_path, method: :delete , class: 'nav-text' do  %>
	  <li class="nav-list">
	  <%= image_tag 'logout.png' %>
	  <br>ログアウト
	  </li>
	<% end %>

	<%= link_to user_path(current_user.id) , class: 'nav-text' do  %>
	  <li class="nav-list">
	  <%= image_tag 'mypage.png' %>
	  <br>マイページ
	  </li>
	<% end %>
</ul>

<% else %>
  <!-- 未ログイン時 -->
  	<!-- ユーザーの会員登録ページに遷移 -->
  	<%= link_to new_user_session_path , class: 'nav-text' do  %>
	  <li class="nav-list">
	  <%= image_tag 'cart.png' %>
	  <br>カート
	  </li>
	<% end %>

	<%= link_to new_user_session_path , class: 'nav-text' do  %>
	  <li class="nav-list">
	  <%= image_tag 'login.png' %>
	  <br>ログイン
	  </li>
	<% end %>

	<%= link_to new_user_registration_path , class: 'nav-text' do  %>
	  <li class="nav-list">
	  <%= image_tag 'mypage.png' %>
	  <br>新規登録
	  </li>
	<% end %>

</ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bacchikoi</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>

    <%= yield %>
  </body>
</html>