config/routes.rb
Rails.application.routes.draw do
  root 'products#index'

  devise_for :admins, controllers: {
  	sessions:      'admins/sessions',
  	passwords:     'admins/passwords',
  	registrations: 'admins/registrations'
  }
  devise_for :users, controllers: {
  	sessions:      'users/sessions',
  	passwords:     'users/passwords',
  	registrations: 'users/registrations'
  }

  get "admins/top"
  get 'products/search' => "products#search", as: "search"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

resources :users, only: [:show, :index, :edit]
resources :purchase_histories
resources :admins
resources :admins_users
resources :admins_products, only: [ :new, :create, :edit, :update, :destroy]
post 'admins_product/:id' => 'admins_products#show'
resources :carts, only: [:show]
resources :products

post '/add_content' => 'carts#add_content'
post '/update_content' => 'carts#update_content'
delete '/delete_content' => 'carts#delete_content'

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
	belongs_to :label
	has_many :products, inverse_of: :artist
	accepts_nested_attributes_for :products, reject_if: :all_blank, allow_destroy: true

	enum genre_name:{JーPOP: 0,洋楽: 1,KーPOP: 2}
end

app/models/cart.rb
class Cart < ApplicationRecord

	has_many :cart_contents, dependent: :destroy
	belongs_to :user

end

app/models/cart_content.rb
class CartContent < ApplicationRecord

	belongs_to :product
	belongs_to :cart

end

app/models/disc.rb
class Disc < ApplicationRecord
	belongs_to :product
	has_many :songs, inverse_of: :disc
	accepts_nested_attributes_for :songs, reject_if: :all_blank, allow_destroy: true

end

app/models/label.rb
class Label < ApplicationRecord
	has_many :artists, inverse_of: :label
	accepts_nested_attributes_for :artists, reject_if: :all_blank, allow_destroy: true

	enum label_name:{ユニバーサルミュージック: 0,ワーナーミュージックジャパン: 1,ソニーミュージックレーベルズ: 2,アニプレックス: 3, ポニーキャニオン: 4}

end

app/models/product.rb
class Product < ApplicationRecord
	# 下記２行cocoon記述
	has_many :discs, inverse_of: :product
	accepts_nested_attributes_for :discs, reject_if: :all_blank, allow_destroy: true

	has_many :jackets
	has_many :purchase_contents
  

	has_many :cart_contents, dependent: :destroy
	has_many :discs, dependent: :destroy
	has_many :jackets, dependent: :destroy
	has_many :purchase_histroys
	belongs_to :artist

	attachment :jacket_image_id

	enum type_name:{シングル: 0,アルバム: 1}
end

app/models/purchase_content.rb
class PurchaseContent < ApplicationRecord
	belongs_to :product
	belongs_to :purchase_history
end

app/models/purchase_history.rb
class PurchaseHistory < ApplicationRecord
	has_many :purchase_contents, dependent: :destroy
	belongs_to :user

	enum delivery_status:{受付: 0,商品準備中: 1,出荷済: 2,キャンセル: 3}
end

app/models/song.rb
class Song < ApplicationRecord

	belongs_to :disc

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :purchase_histories, dependent: :destroy
  has_one :cart

  validates :name, presence: true, length: { minimum: 2, maximum: 30 }
  validates :name_kana, presence: true, format: {with: /\A([ァ-ン]|ー)+\z/, :message =>'はカタカナで入力して下さい。'}
  validates :postal_code, presence: true, format: {with: /\A\d{3}[-]\d{4}$|^\d{3}[-]\d{2}$|^\d{3}\z/, :message =>'は有効でありません。'}
  validates :address, presence: true
  validates :tel, presence: true, format: {with: /\A[0-9]{3}-[0-9]{4}-[0-9]{4}\z/, :message =>'は有効でありません。'}

# soft_deletable

#   # Deviseを使うと、問答無用でemailがユニーク扱いになる。
#   # それだと論理削除した際に再登録できないので、一旦emailに関する検証を削除する
#   # https://gist.github.com/brenes/4503386
#   _validators.delete(:email)
#   _validate_callbacks.each do |callback|
#     if callback.raw_filter.respond_to? :attributes
#       callback.raw_filter.attributes.delete :email
#     end
#   end

#   # emailのバリデーションを定義し直す
#   validates :email, presence: true
#   validates_format_of :email, with: Devise.email_regexp, if: :email_changed?
#   validates_uniqueness_of :email, scope: :deleted_at, if: :email_changed?

#   def self.find_for_authentication(warden_conditions)
#     without_soft_destroyed.where(email: warden_conditions[:email]).first
#   end

end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController

def top
	
end

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  # before_action :setup_cart_content!, only: [:add_content, :update_content, :delete_content]

  def show
    if session[:user_id].nil?
    @cart = Cart.find_by(params[:id])
    @cart_contents = @cart.cart_contents
  else
    session[:user_id] = params[:user_id]
  end
end

  # 商品一覧画面から、「商品購入」を押した時のアクション
  def add_content
    if @cart_content.blank?
      @cart_content = current_cart.cart_contents.build(product_id: params[:product_id])
    end

    @cart_content.quantity += params[:item_quantity].to_i
    @cart_content.save
    redirect_to current_cart
  end

  # カート詳細画面から、「更新」を押した時のアクション
  def update_content
    @cart_content.update(item_quantity: params[:item_quantity].to_i)
    redirect_to current_cart
  end

# カート詳細画面から、「削除」を押した時のアクション
  def delete_content
    @cart_content.destroy
    redirect_to current_cart
  end

  private

  # def setup_cart_content!
  #   @cart_content = current_cart.cart_contents.find_by(product_id: params[:product_id])
  # end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def new
    @products = Product.new
  end

  def index
    @q = Product.ransack(params[:q])
  	@products = @q.result(distinct: true)
    @products = Product.all
  end


  def show
    @product = Product.find(params[:id])
    @q = Product.ransack(params[:q])
    @products = @q.result(distinct: true)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :correct_user, only: [:edit, :update ,:show]

  def cansel
  end

  def create
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to roots
  end

  def edit
    @user = User.find(params[:id])
  end

  def new
  end

  def show
    @user = User.find(params[:id])
    @q = Product.ransack(params[:q])
    @products = @q.result(distinct: true)
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to root_path
  end

  private
  def correct_user
    user = User.find(params[:id])
    if current_user != user
      redirect_to root_path
    end
  end

end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/admins_products_helper.rb
module AdminsProductsHelper
end

app/helpers/admins_users_helper.rb
module AdminsUsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/carts/show.html.erb
<%= render 'layouts/header' %>

<div class="container">
<% if user_signed_in? %>
  <p>ようこそ、<%= current_user.name %> 様</p>
<% else %>
  <p>ようこそ、ゲスト様</p>
<% end %>

<p><%= current_user.name %> 様のカート内</p>
<% @cart_contents.each do |cart_content| %>
<div class="row my-2 mx-1 p-3 box">
	<div class="col-4">
		<div class="box-jacket">
			<%= image_tag 'test.jpg'%>
		</div>
	</div>
	<div class="col-8">
		<div class="box-song"><a href="#"><%= cart_content.product.product_name %></a></div>
		<div class="hr my-1"><hr></div>
		<div class="box-artist"><a href="#"><%= cart_content.product.artist.artist_name %></a></div>
		<div class="hr my-1"><hr></div>
		<div class="box-price">価格（税込）：<%= cart_content.product.price %></div>
		<div class="hr my-1"><hr></div>
		<div class="box-stock">個数：<%= cart_content.product.number_of_stock %>
			<select name="cnt" style="margin-right: 0.5em">
			<option value="0">0</option>
			<option value="1" selected>1</option>
			<option value="2">2</option>
			<option value="3">3</option>
			<option value="4">4</option>
			<option value="5">5</option>
			<option value="6">6</option>
			<option value="7">7</option>
			<option value="8">8</option>
			<option value="9">9</option>
			</select>個
		</div>
		<div class="hr my-1"><hr></div>
		<div class="row mt-2 mx-auto">
			<div class="col-6">
				<button type="button" class="btn btn-warning btn-block">取消</button>
			</div>
			<div class="col-6">
				<button type="button" class="btn btn-warning btn-block">購入</button>
			</div>
		</div>
	</div>
</div><!-- row my-2 mx-1 p-3 box -->
<% end %>

app/views/products/index.html.erb
<%= render 'layouts/header' %>

<div class="container">

<% if user_signed_in? %>
  <p>ようこそ、<%= current_user.name %> 様</p>
<% else %>
  <p>ようこそ、ゲスト様</p>
<% end %>

<!--ransackフォーム-->
<div class="input-group flex-nowrap mb-3">

              <%= search_form_for @q, class:"input-group-prepend w-100", url: search_path do |f| %>

                <%= f.search_field :price_cont, class:"form-control col-10", placeholder:"曲・アーティストを探す" %>

                <%= f.submit '検索', class: "btn btn-outline-secondary  col-2" %>

              <% end %>

</div>
  <!--ransackフォーム-->



<div id="top-image" class="text-center"></div>

<!-- 下記はカラオケ人気曲順です -->
<h2 class="mt-4">カラオケ人気曲ランキング</h2>
<div class="card p-3">
  <div class="row pl-2">1位：<%= link_to 'Love so sweet／嵐', product_path(1) %></div>
  <div class="row pl-2">2位：<%= link_to '女々しくて／ゴルデンボンバー' %></div>
  <div class="row pl-2">3位：<%= link_to '純恋歌／湘南乃風' %></div>
  <div class="row pl-2">4位：<%= link_to 'クリスマスソング／バックナンバー' %></div>
  <div class="row pl-2">5位：<%= link_to 'リンダリンダ／ブルーハーツ' %></div>
</div>

<!-- 下記は歌いやすい曲ランキングベスト５（ベタ打ち？）です。 -->
<div class="ranking">
  <h3 class="mt-4">20代男性が歌いやすいカラオケ曲ベスト5</h3>
  <div class="row mb-2 p-3 box">
      <div class="col-4">
        <div class="mx-auto text-center">CDシングル</div>
        <div class="box-jacket"><%= image_tag 'Ulfuls_Ashitagaarusa.jpg'%></div>
      </div>
      <div class="col-8 mt-3">
        <div class="box-song"><a href="#">明日があるさ</a></div>
        <div class="hr my-1"><hr></div>
        <div class="box-artist"><a href="#">ウルフルズ</a></div>
        <div class="hr my-1"><hr></div>
        <div class="box-price">価格（税込）：¥1,000</div>
        <div class="hr my-1"><hr></div>
        <div class="box-stock">在庫状況：在庫あり</div>
        <div class="mx-auto text-center">
          <button type="button" class="btn btn-warning mt-3">カートに入れる</button>
        </div>
      </div>
    </div><!-- row mb-2 p-3 box -->

    <div class="row mb-2 p-3 box">
      <div class="col-4">
        <div class="mx-auto text-center">CDアルバム</div>
        <div class="box-jacket"><%= image_tag 'Mongok800_chiisanakoinouta.jpg'%></div>
      </div>
      <div class="col-8 mt-3">
        <div class="box-song"><a href="#">小さな恋の歌</a></div>
        <div class="hr my-1"><hr></div>
        <div class="box-artist"><a href="#">モンゴル800</a></div>
        <div class="hr my-1"><hr></div>
        <div class="box-price">価格（税込）：¥2,160</div>
        <div class="hr my-1"><hr></div>
        <div class="box-stock">在庫状況：在庫あり</div>
        <div class="mx-auto text-center">
          <button type="button" class="btn btn-warning mt-3">カートに入れる</button>
        </div>
      </div>
    </div>

    <div class="row mb-2 p-3 box">
      <div class="col-4">
        <div class="mx-auto text-center">CDシングル</div>
        <div class="box-jacket"><%= image_tag 'Fukuyamamasaharu_Sakurazaka.jpg'%></div>
      </div>
      <div class="col-8 mt-3">
        <div class="box-song"><a href="#">桜坂</a></div>
        <div class="hr my-1"><hr></div>
        <div class="box-artist"><a href="#">福山雅治</a></div>
        <div class="hr my-1"><hr></div>
        <div class="box-price">価格（税込）：¥1,380</div>
        <div class="hr my-1"><hr></div>
        <div class="box-stock">在庫状況：在庫あり</div>
        <div class="mx-auto text-center">
          <button type="button" class="btn btn-warning mt-3">カートに入れる</button>
        </div>
      </div>
    </div>

    <div class="row mb-2 p-3 box">
      <div class="col-4">
        <div class="mx-auto text-center">CDシングル</div>
        <div class="box-jacket"><%= image_tag 'Spitz_Robinson.jpg'%></div>
      </div>
      <div class="col-8 mt-3">
        <div class="box-song"><a href="#">ロビンソン</a></div>
        <div class="hr my-1"><hr></div>
        <div class="box-artist"><a href="#">スピッツ</a></div>
        <div class="hr my-1"><hr></div>
        <div class="box-price">価格（税込）：¥1,180</div>
        <div class="hr my-1"><hr></div>
        <div class="box-stock">在庫状況：在庫あり</div>
        <div class="mx-auto text-center">
          <button type="button" class="btn btn-warning mt-3">カートに入れる</button>
        </div>
      </div>
    </div>

    <div class="row mb-2 p-3 box">
      <div class="col-4">
        <div class="mx-auto text-center">CDシングル</div>
        <div class="box-jacket"><%= image_tag 'Sign_MrChirldren.jpg'%></div>
      </div>
      <div class="col-8 mt-3">
        <div class="box-song"><a href="#">Sign</a></div>
        <div class="hr my-1"><hr></div>
        <div class="box-artist"><a href="#">Mr.Children</a></div>
        <div class="hr my-1"><hr></div>
        <div class="box-price">価格（税込）：¥980</div>
        <div class="hr my-1"><hr></div>
        <div class="box-stock">在庫状況：在庫あり</div>
        <div class="mx-auto text-center">
          <button type="button" class="btn btn-warning mt-3">カートに入れる</button>
        </div>
      </div>
    </div>

</div><!-- ranking -->

</div><!-- container -->

<footer class="footer mt-3 p-2 bg-warning text-light">
  <div class="col-12 text-center">©︎inflatop.inc</div>
</footer>

app/views/products/show.html.erb
<%= render 'layouts/header' %>

<div class="container">

<% if user_signed_in? %>
  <p>ようこそ、<%= current_user.name %> 様</p>
<% else %>
  <p>ようこそ、ゲスト様</p>
<% end %>

<!--ransackフォーム-->
<div class="input-group flex-nowrap mb-3">

              <%= search_form_for @q, class:"input-group-prepend w-100", url: search_path do |f| %>

                <%= f.search_field :price_cont, class:"form-control col-10", placeholder:"曲・アーティストを探す" %>

                <%= f.submit '検索', class: "btn btn-outline-secondary  col-2" %>

              <% end %>

              <% if params[:q].present? && params[:q][:price_cont].present? %>
                Search name: <%= params[:q][:price_cont] %>
              <% end %>
</div>
  <!--ransackフォーム-->

<div class="row mb-2 p-3 box">
  <div class="col-4">
    <div class="mx-auto text-center"><%= @product.type_name %></div>
    <div class="box-jacket"><%= image_tag 'Ulfuls_Ashitagaarusa.jpg', fallback: "no_image.jpg" %></div>
    <div class="box-jacket"><%#<%= image_tag @product.jacket_image_id, fallback: "no_image.jpg" %></div>
  </div>
  <div class="col-8 mt-3">
    <div class="box-song"><%= @product.product_name %></div>
    <div class="hr my-1"><hr></div>
    <div class="box-artist"><%= @product.artist.artist_name %></div>
    <div class="hr my-1"><hr></div>
    <div class="box-price">価格（税込）：¥<%= @product.price %></div>
    <div class="hr my-1"><hr></div>
    <div class="box-stock">在庫状況：<%= @product.number_of_stock %>
    </div>
    <div class="mx-auto text-center">
      <button type="button" class="btn btn-warning mt-3">カートに入れる</button>
    </div>
  </div>
</div>

<div class="row mb-2 p-3 card">
	<p>ジャンル名：<%= @product.artist.genre_name %></p>
	<p>レーベル名：<%= @product.artist.label.label_name %></p>
</div>

<div class="row mb-2 p-3 card">
	<p>収録曲</p>
		<% @product.discs.each do |disc| %>
			<p>【<%= disc.disc_name %>】</p>
			<% disc.songs.each do |song| %>
				<ul>
					<li><%= song.song_name %></li>
				</ul>
			<% end %>
		<% end %>
</div>

<div class="row mb-2 p-3 card">
	<p>商品詳細</p>
	<div><%= @product.product_introduction %></div>
</div>

<div class="row mb-2 p-3 card">
	<p>スタッフコメント</p>
	<div><%= @product.staff_comment %></div>
</div>

</div><!-- container -->

<footer class="footer mt-3 p-2 bg-warning text-light">
  <div class="col-12 text-center">©︎inflatop.inc</div>
</footer>